"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var monitorsRequestController_1 = require("../monitors/controllers/monitorsRequestController");
var monitorsCreateController_1 = require("../monitors/controllers/monitorsCreateController");
var monitorsUpdateController_1 = require("../monitors/controllers/monitorsUpdateController");
var monitorsDeleteController_1 = require("../monitors/controllers/monitorsDeleteController");
var router = express_1.default.Router();
router.get('/monitors', monitorsRequestController_1.default);
router.post('/monitors', monitorsCreateController_1.default);
router.put('/monitors/:id', monitorsUpdateController_1.default);
router.delete('/monitors/:id', monitorsDeleteController_1.default);
exports.default = router;
